type User {
  _id: ID!
  email: String
  password: String

input InputUserType {
  email: String!
  password: String!
}

type Mutation {
  createUser(body: InputUserType!): User
  updateUser(_id: ID!, body: InputUserType!): User
  deleteUser(_id: ID!): User
}

type UserEdgesType {
  edges: [User]
  pagination: PaginationType!
}

type Query {
  readUser(_id: ID!): User
  listUser(page: Int, limit: Int, sortBy: String, sortOrder: String): UserEdgesType
  searchUser(limit: Int, query: String!, fields: String!): [User]
}
