import type { NextPage } from 'next';

import Head from 'next/head';

import PlaceList from '@/components/QuestionaireList';
import Navbars from '@/components/navbar';
import QuestionaireList from '@/components/QuestionaireList';
const Home: NextPage = () => {
  return (
    <div>
		<Head>
			<title>Management of Questionaire</title>
			<meta name="description" content="Generated by create next app" />
			<link rel="icon" href="/favicon.ico" />
		</Head>
        <Navbars />
        <QuestionaireList />
    </div>
  );
};

export default Home;
